config/routes.rb
Rails.application.routes.draw do
  get 'favourites/new'

  get '/login', to: 'session#new'
  post '/login', to: 'session#create'
  delete '/logout', to: 'session#destroy'

  get '/favourites', to: 'favourites#favourites'
  delete '/remove_favourite', to: 'favourites#destroy'

  resources :petrol_stations
  resources :refuellings
  resources :cars
  resources :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/petrol_station.rb
class PetrolStation < ApplicationRecord
  has_many :refuellings
  has_and_belongs_to_many :users
end

app/controllers/petrol_stations_controller.rb
class PetrolStationsController < ApplicationController
  before_action :set_petrol_station, only: [:show, :edit, :update, :destroy]

  def user_likes_station?(petrol_station_id)
    !current_user.petrol_stations.find_by_id(petrol_station_id).nil?
  end
  helper_method :user_likes_station?

  # GET /petrol_stations
  # GET /petrol_stations.json
  def index
    @petrol_stations = PetrolStation.all
  end

  # GET /petrol_stations/1
  # GET /petrol_stations/1.json
  def show
  end

  # GET /petrol_stations/new
  def new
    @petrol_station = PetrolStation.new
  end

  # GET /petrol_stations/1/edit
  def edit
  end

  # POST /petrol_stations
  # POST /petrol_stations.json
  def create
    @petrol_station = PetrolStation.new(petrol_station_params)

    respond_to do |format|
      if @petrol_station.save
        format.html { redirect_to @petrol_station, notice: 'Petrol station was successfully created.' }
        format.json { render :show, status: :created, location: @petrol_station }
      else
        format.html { render :new }
        format.json { render json: @petrol_station.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /petrol_stations/1
  # PATCH/PUT /petrol_stations/1.json
  def update
    respond_to do |format|
      if @petrol_station.update(petrol_station_params)
        format.html { redirect_to @petrol_station, notice: 'Petrol station was successfully updated.' }
        format.json { render :show, status: :ok, location: @petrol_station }
      else
        format.html { render :edit }
        format.json { render json: @petrol_station.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /petrol_stations/1
  # DELETE /petrol_stations/1.json
  def destroy
    @petrol_station.destroy
    respond_to do |format|
      format.html { redirect_to petrol_stations_url, notice: 'Petrol station was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_petrol_station
      @petrol_station = PetrolStation.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def petrol_station_params
      params.require(:petrol_station).permit(:name, :street, :city, :postal_code, :pb95_price, :pb98_price, :on_price, :gas_price, :likes, :unlikes)
    end
end

app/helpers/petrol_stations_helper.rb
module PetrolStationsHelper
end

app/views/petrol_stations/_form.html.erb
<%= form_with(model: petrol_station, local: true) do |form| %>
  <% if petrol_station.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(petrol_station.errors.count, "error") %> prohibited this petrol_station from being saved:</h2>

      <ul>
      <% petrol_station.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :petrol_station_name %>
  </div>

  <div class="field">
    <%= form.label :street %>
    <%= form.text_field :street, id: :petrol_station_street %>
  </div>

  <div class="field">
    <%= form.label :city %>
    <%= form.text_field :city, id: :petrol_station_city %>
  </div>

  <div class="field">
    <%= form.label :postal_code %>
    <%= form.text_field :postal_code, id: :petrol_station_postal_code %>
  </div>

  <div class="field">
    <%= form.label :pb95_price %>
    <%= form.text_field :pb95_price, id: :petrol_station_pb95_price %>
  </div>

  <div class="field">
    <%= form.label :pb98_price %>
    <%= form.text_field :pb98_price, id: :petrol_station_pb98_price %>
  </div>

  <div class="field">
    <%= form.label :on_price %>
    <%= form.text_field :on_price, id: :petrol_station_on_price %>
  </div>

  <div class="field">
    <%= form.label :gas_price %>
    <%= form.text_field :gas_price, id: :petrol_station_gas_price %>
  </div>

  <div class="field">
    <%= form.label :likes %>
    <%= form.number_field :likes, id: :petrol_station_likes %>
  </div>

  <div class="field">
    <%= form.label :unlikes %>
    <%= form.number_field :unlikes, id: :petrol_station_unlikes %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/petrol_stations/edit.html.erb
<h1>Editing Petrol Station</h1>

<%= render 'form', petrol_station: @petrol_station %>

<%= link_to 'Show', @petrol_station %> |
<%= link_to 'Back', petrol_stations_path %>

app/views/petrol_stations/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Petrol Stations</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Street</th>
      <th>City</th>
      <th>Postal code</th>
      <th>Pb95 price</th>
      <th>Pb98 price</th>
      <th>On price</th>
      <th>Gas price</th>
      <th>Likes</th>
      <th>Unlikes</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @petrol_stations.each do |petrol_station| %>
      <tr>
        <td><%= petrol_station.name %></td>
        <td><%= petrol_station.street %></td>
        <td><%= petrol_station.city %></td>
        <td><%= petrol_station.postal_code %></td>
        <td><%= petrol_station.pb95_price %></td>
        <td><%= petrol_station.pb98_price %></td>
        <td><%= petrol_station.on_price %></td>
        <td><%= petrol_station.gas_price %></td>
        <td><%= petrol_station.likes %></td>
        <td><%= petrol_station.unlikes %></td>
        <td><%= petrol_station.city %></td>
        <% if user_likes_station?(petrol_station.id) %>
          <td><%= link_to "Delete from favourites",
          { :controller => :favourites, :action => :destroy,
            :petrol_station_id => petrol_station.id }, :method => :delete %></td>
        <% else %>
          <td><%= link_to 'Add to favourites', { :controller => 'favourites',
          :action => 'new', :petrol_station_id => petrol_station.id } %></td>
        <% end %>
        <td><%= link_to 'Show', petrol_station %></td>
        <td><%= link_to 'Edit', edit_petrol_station_path(petrol_station) %></td>
        <td><%= link_to 'Destroy', petrol_station, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Petrol Station', new_petrol_station_path %>

app/views/petrol_stations/new.html.erb
<h1>New Petrol Station</h1>

<%= render 'form', petrol_station: @petrol_station %>

<%= link_to 'Back', petrol_stations_path %>

app/views/petrol_stations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @petrol_station.name %>
</p>

<p>
  <strong>Street:</strong>
  <%= @petrol_station.street %>
</p>

<p>
  <strong>City:</strong>
  <%= @petrol_station.city %>
</p>

<p>
  <strong>Postal code:</strong>
  <%= @petrol_station.postal_code %>
</p>

<p>
  <strong>Pb95 price:</strong>
  <%= @petrol_station.pb95_price %>
</p>

<p>
  <strong>Pb98 price:</strong>
  <%= @petrol_station.pb98_price %>
</p>

<p>
  <strong>On price:</strong>
  <%= @petrol_station.on_price %>
</p>

<p>
  <strong>Gas price:</strong>
  <%= @petrol_station.gas_price %>
</p>

<p>
  <strong>Likes:</strong>
  <%= @petrol_station.likes %>
</p>

<p>
  <strong>Unlikes:</strong>
  <%= @petrol_station.unlikes %>
</p>

<%= link_to 'Edit', edit_petrol_station_path(@petrol_station) %> |
<%= link_to 'Back', petrol_stations_path %>